### ISSUE TITLE
Can't add Clock gadget

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/editor-app#136]
Reproduction Steps
 - Add a placeholder
 - Press "Add Playlist Item"
 - Search for Clock and Add it.

Expected Results
Playlist Item modal should appear and a message should be displayed warning that gadgets are not supported by the new Editor.

Actual Results
After clicking the Add button, no modal is shown and an error is thrown in the console.

**Comment by ezequielc** [comment]
@ByronDarlison The issue happens because this gadget is missing the gadgetType property when retrieved from Store. We use that property to differentiate widgets from gadgets.
 
Should we expected the missing property and fix it in Editor or would be better to fix it in Store?
Also, I tested other gadgets and they worked fine, but we should check if more gadgets have that property missing. Thanks

**Comment by ByronDarlison** [comment]
@ezequielc ah ha. Thanks! @brianloosbrock @robb-price can you take a look at this and let us know your thoughts. Thanks

**Comment by ezequielc** [comment]
Photo Album has the same issue as reported at https://github.com/Rise-Vision/editor-app/issues/131 . Cheers

**Comment by brianloosbrock** [comment]
@ezequielc We'll look into it Monday. Thanks

**Comment by alex-deaconu** [comment]
After some research, it appears the Issue is due to Gadgets that have not been saved in the RVA since we introduced the `gadgetType` field (with Widgets). These include the following Store products:
``
Text Scroller, Clock, Directory, Google Maps, Foursquare, Headline News, Photo Album
``

Saving the Gadget fixes the issue, so they all should be re-saved in the RVA and verified. 

Thanks.

**Comment by robb-price** [comment]
Doing this now.

Should be done in 10 minutes.

**Comment by robb-price** [comment]
Fixed for: 
Clock
Foursquare
Google Maps
Photo Album
Text Scroller
Directory
Headline News
